name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Only if needed for generating static files

      - name: Build static site
        run: |
          # Command to generate static files from your Python app
          # For example, if using Flask-Frozen, you might run:
          # flask freeze
          # Or for Django, ensure your static files are collected
          echo "Building static site..."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./nomad/templates/  # Update this to your build/static directory